[package]
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
name    = "startin"
version = "0.6.1"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
license = "MIT"
homepage="https://github.com/hugoledoux/startin_python"
repository="https://github.com/hugoledoux/startin_python"
documentation="https://github.com/hugoledoux/startin_python"
description = "A Delaunay triangulator for terrains"
edition = "2018"


[dependencies]
startin = "0.4.7"


[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]


[lib]
name = "startin"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-dist = ["toml==0.10.0"]
classifier=["License :: OSI Approved :: MIT License"]