[package]
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
name    = "startin"
version = "0.1.2"
edition = "2018"


[dependencies]
startin = "0.4.0"


[dependencies.pyo3]
version = "0.7.0-alpha.1"
features = ["extension-module"]

[lib]
name = "startin"
crate-type = ["cdylib"]
