name: Build sphinx docs + gh-pages

on:
  push:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/setup-python@v2        
    
    - uses: actions/checkout@v2

    - uses: syphar/restore-virtualenv@v1
      id: myvenv
      
    
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        manylinux: auto
        command: develop

    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
      with:
        branch: master
        dir_docs: docs
        sphinxopts: '-b html'       


